### ISSUE TITLE
Redes sociales superpuestas con el botón de enviar

### ISSUE THREAD

**Issue by elverdavid-dev** [Deniisolo/denisolo#41]
He revisado tu portafolio y he notado un pequeño problema de diseño en la sección de contacto. Las redes sociales están posicionadas sobre el botón de enviar, lo cual impide que se pueda utilizar correctamente el formulario. Para ilustrar mejor el problema, he realizado un fork de tu repositorio y he añadido un fondo rojo a esa sección para que el problema sea más visible.
![form](https://github.com/user-attachments/assets/58620527-18cd-4283-aba3-414c987917fd)

**Comment by Deniisolo** [comment]
Hola David, sí, si lo noté y lo peor es que lo subí 😰 voy a corregirlo 🫣. Muchas gracias por escribirme. 😄

Atentamente,
Denis Alvarez - Deniisolo
________________________________
De: Elver David ***@***.***>
Enviado: jueves, 1 de agosto de 2024 21:54
Para: Deniisolo/denisolo ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [Deniisolo/denisolo] Redes sociales superpuestas con el botón de enviar (Issue #41)


He revisado tu portafolio y he notado un pequeño problema de diseño en la sección de contacto. Las redes sociales están posicionadas sobre el botón de enviar, lo cual impide que se pueda utilizar correctamente el formulario. Para ilustrar mejor el problema, he realizado un fork de tu repositorio y he añadido un fondo rojo a esa sección para que el problema sea más visible.
form.png (view on web)<https://github.com/user-attachments/assets/58620527-18cd-4283-aba3-414c987917fd>
